# Generated by Django 6.0.1 on 2026-02-06 18:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='odontologo',
            options={'ordering': ['user__last_name', 'user__first_name'], 'verbose_name': 'Odontólogo', 'verbose_name_plural': 'Odontólogos'},
        ),
        migrations.AddField(
            model_name='odontologo',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='odontologo',
            name='anos_experiencia',
            field=models.IntegerField(default=0, verbose_name='Años de experiencia'),
        ),
        migrations.AddField(
            model_name='odontologo',
            name='especialidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Especialidad'),
        ),
        migrations.AddField(
            model_name='odontologo',
            name='fecha_alta',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de alta'),
        ),
        migrations.AddField(
            model_name='odontologo',
            name='horario_atencion',
            field=models.TextField(blank=True, null=True, verbose_name='Horario de atención'),
        ),
        migrations.AddField(
            model_name='odontologo',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Matrícula Profesional'),
        ),
    ]
