# Generated by Django 6.0.1 on 2026-02-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologos', '0003_alter_odontologo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odontologo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
