# Generated by Django 5.2.7 on 2026-02-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologos', '0004_alter_odontologo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odontologo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
