# Generated by Django 6.0.1 on 2026-02-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologos', '0005_alter_odontologo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontologo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('activo', 'Activo'), ('suspendido', 'Suspendido')], default='pendiente', help_text='Estado actual del odontólogo en el sistema', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='odontologo',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación'),
        ),
        migrations.AddField(
            model_name='odontologo',
            name='fecha_suspension',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de suspensión'),
        ),
        migrations.AddField(
            model_name='odontologo',
            name='motivo_suspension',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de suspensión'),
        ),
        migrations.AlterField(
            model_name='odontologo',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo (deprecado)'),
        ),
        migrations.AlterField(
            model_name='odontologo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
