# Generated by Django 6.0.1 on 2026-03-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologos', '0006_odontologo_estado_odontologo_fecha_aprobacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontologo',
            name='terms_accepted',
            field=models.BooleanField(default=False, help_text='Indica si el odontólogo ha aceptado los términos y condiciones del servicio', verbose_name='Términos aceptados'),
        ),
        migrations.AddField(
            model_name='odontologo',
            name='terms_accepted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aceptación de términos'),
        ),
    ]
