# Generated by Django 6.0.1 on 2026-03-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odontologos', '0007_add_terms_accepted_field'),
    ]

    operations = [
    ]
