# Generated by Django 6.0.1 on 2026-03-09 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odontologos', '0008_set_terms_for_existing_odontologos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='odontologo',
            name='terms_accepted',
        ),
        migrations.RemoveField(
            model_name='odontologo',
            name='terms_accepted_date',
        ),
    ]
