# Generated by Django 6.0.1 on 2026-03-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologos', '0009_remove_odontologo_terms_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontologo',
            name='terms_accepted',
            field=models.BooleanField(default=False, verbose_name='Términos aceptados'),
        ),
        migrations.AddField(
            model_name='odontologo',
            name='terms_accepted_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aceptación de términos'),
        ),
    ]
