# Generated by Django 6.0.1 on 2026-03-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologos', '0010_add_terms_accepted_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontologo',
            name='storage_limit',
            field=models.BigIntegerField(default=1073741824, help_text='Límite máximo de almacenamiento en bytes (default: 1 GB)', verbose_name='Límite de almacenamiento (bytes)'),
        ),
        migrations.AddField(
            model_name='odontologo',
            name='storage_used',
            field=models.BigIntegerField(default=0, help_text='Bytes de archivos subidos a Cloudinary por este odontólogo', verbose_name='Almacenamiento usado (bytes)'),
        ),
    ]
