# Generated by Django 6.0.1 on 2026-03-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologos', '0011_odontologo_storage_limit_odontologo_storage_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontologo',
            name='consultorio',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Dirección del consultorio'),
        ),
    ]
