# Generated by Django 6.0.1 on 2026-09-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologos', '0014_populate_default_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontologo',
            name='snake_high_score',
            field=models.IntegerField(default=0, help_text='Puntaje máximo alcanzado en el minijuego Snake', verbose_name='Récord Snake'),
        ),
    ]
