# Generated by Django 6.0.1 on 2026-09-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologos', '0015_odontologo_snake_high_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontologo',
            name='aviso_prueba_dias',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='odontologo',
            name='es_demo',
            field=models.BooleanField(db_default=False, default=False, verbose_name='Cuenta demo'),
        ),
        migrations.AddField(
            model_name='odontologo',
            name='fecha_fin_prueba',
            field=models.DateTimeField(blank=True, help_text='Vacío si la cuenta ya está suscripta', null=True, verbose_name='Fin del período de prueba'),
        ),
    ]
