# Generated by Django 6.0.1 on 2026-09-30 21:07

from django.db import migrations, models


def crear_links(apps, schema_editor):
    """Genera el link de turnos (slug) de los odontólogos que ya existen."""
    from django.utils.text import slugify

    Odontologo = apps.get_model('odontologos', 'Odontologo')
    for odontologo in Odontologo.objects.select_related('user').filter(slug__isnull=True).order_by('id'):
        base = slugify(f'{odontologo.user.first_name} {odontologo.user.last_name}')[:70] or 'odontologo'
        slug, n = base, 1
        while Odontologo.objects.filter(slug=slug).exists():
            n += 1
            slug = f'{base}-{n}'
        odontologo.slug = slug
        odontologo.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('odontologos', '0016_prueba_gratis_y_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontologo',
            name='slug',
            field=models.SlugField(blank=True, max_length=80, null=True, unique=True, verbose_name='Link de turnos'),
        ),
        # Solo completa un campo nuevo; al revertir no hace falta deshacer nada
        migrations.RunPython(crear_links, migrations.RunPython.noop),
    ]
