# Generated by Django 6.0.1 on 2026-10-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologos', '0017_link_turnos'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontologo',
            name='terms_version',
            field=models.CharField(blank=True, db_default='', default='', max_length=20, verbose_name='Versión de términos aceptada'),
        ),
    ]
