# Generated by Django 6.0.1 on 2026-02-06 18:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['user__last_name', 'user__first_name'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AddField(
            model_name='paciente',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='alergias',
            field=models.TextField(blank=True, null=True, verbose_name='Alergias'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='antecedentes_medicos',
            field=models.TextField(blank=True, null=True, verbose_name='Antecedentes Médicos'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_alta',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de alta'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='numero_afiliado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Afiliado'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='obra_social',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Obra Social'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='DNI'),
        ),
    ]
