# Generated by Django 6.0.1 on 2026-02-07 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_alter_paciente_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('sigla', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sigla')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Obra Social',
                'verbose_name_plural': 'Obras Sociales',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='alergias',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='antecedentes_medicos',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='numero_afiliado',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='obra_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='pacientes.obrasocial', verbose_name='Obra Social'),
        ),
    ]
