# Generated by Django 6.0.1 on 2026-02-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_poblar_obras_sociales'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='alergias',
            field=models.TextField(blank=True, null=True, verbose_name='Alergias'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='antecedentes_medicos',
            field=models.TextField(blank=True, null=True, verbose_name='Antecedentes Médicos'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='numero_afiliado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Afiliado'),
        ),
    ]
