# Generated by Django 6.0.1 on 2026-02-10 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologos', '0006_odontologo_estado_odontologo_fecha_aprobacion_and_more'),
        ('pacientes', '0007_alter_obrasocial_id_alter_paciente_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obrasocial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción del seguimiento')),
                ('imagen_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de imagen')),
                ('fecha_atencion', models.DateField(verbose_name='Fecha de atención')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('odontologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_realizados', to='odontologos.odontologo', verbose_name='Odontólogo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
                'ordering': ['-fecha_atencion', '-fecha_creacion'],
            },
        ),
    ]
