# Generated by Django 6.0.1 on 2026-02-12 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0008_alter_obrasocial_id_alter_paciente_id_seguimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('imagen', 'Imagen'), ('documento', 'Documento')], max_length=20, verbose_name='Tipo de archivo')),
                ('url', models.URLField(max_length=500, verbose_name='URL del archivo en Cloudinary')),
                ('nombre_original', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre original del archivo')),
                ('public_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Public ID de Cloudinary')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida')),
                ('seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='pacientes.seguimiento', verbose_name='Seguimiento')),
            ],
            options={
                'verbose_name': 'Archivo de Seguimiento',
                'verbose_name_plural': 'Archivos de Seguimiento',
                'ordering': ['fecha_subida'],
            },
        ),
    ]
