# Generated by Django 6.0.1 on 2026-02-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0009_seguimientoarchivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='obra_social_otra',
            field=models.CharField(blank=True, help_text='Nombre de obra social si no está en la lista', max_length=200, null=True, verbose_name='Otra Obra Social'),
        ),
    ]
