# Generated by Django 6.0.1 on 2026-02-12 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologos', '0006_odontologo_estado_odontologo_fecha_aprobacion_and_more'),
        ('pacientes', '0010_add_obra_social_otra'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieza_dental', models.IntegerField(choices=[(11, '11 - Incisivo Central Superior Derecho'), (12, '12 - Incisivo Lateral Superior Derecho'), (13, '13 - Canino Superior Derecho'), (14, '14 - Primer Premolar Superior Derecho'), (15, '15 - Segundo Premolar Superior Derecho'), (16, '16 - Primer Molar Superior Derecho'), (17, '17 - Segundo Molar Superior Derecho'), (18, '18 - Tercer Molar Superior Derecho'), (21, '21 - Incisivo Central Superior Izquierdo'), (22, '22 - Incisivo Lateral Superior Izquierdo'), (23, '23 - Canino Superior Izquierdo'), (24, '24 - Primer Premolar Superior Izquierdo'), (25, '25 - Segundo Premolar Superior Izquierdo'), (26, '26 - Primer Molar Superior Izquierdo'), (27, '27 - Segundo Molar Superior Izquierdo'), (28, '28 - Tercer Molar Superior Izquierdo'), (31, '31 - Incisivo Central Inferior Izquierdo'), (32, '32 - Incisivo Lateral Inferior Izquierdo'), (33, '33 - Canino Inferior Izquierdo'), (34, '34 - Primer Premolar Inferior Izquierdo'), (35, '35 - Segundo Premolar Inferior Izquierdo'), (36, '36 - Primer Molar Inferior Izquierdo'), (37, '37 - Segundo Molar Inferior Izquierdo'), (38, '38 - Tercer Molar Inferior Izquierdo'), (41, '41 - Incisivo Central Inferior Derecho'), (42, '42 - Incisivo Lateral Inferior Derecho'), (43, '43 - Canino Inferior Derecho'), (44, '44 - Primer Premolar Inferior Derecho'), (45, '45 - Segundo Premolar Inferior Derecho'), (46, '46 - Primer Molar Inferior Derecho'), (47, '47 - Segundo Molar Inferior Derecho'), (48, '48 - Tercer Molar Inferior Derecho')], verbose_name='Pieza Dental')),
                ('estado', models.CharField(choices=[('sano', 'Sano'), ('caries', 'Caries'), ('obturado', 'Obturado'), ('extraccion', 'Extracción indicada'), ('ausente', 'Ausente'), ('corona', 'Corona'), ('endodoncia', 'Endodoncia'), ('protesis', 'Prótesis'), ('implante', 'Implante'), ('otro', 'Otro')], default='sano', max_length=20, verbose_name='Estado')),
                ('descripcion', models.TextField(verbose_name='Descripción/Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('odontologo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_dentales_realizados', to='odontologos.odontologo', verbose_name='Odontólogo')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_dentales', to='pacientes.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Registro Dental',
                'verbose_name_plural': 'Registros Dentales',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
