# Generated by Django 6.0.1 on 2026-02-19 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologos', '0006_odontologo_estado_odontologo_fecha_aprobacion_and_more'),
        ('pacientes', '0011_registrodental'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrodental',
            options={'ordering': ['pieza_dental'], 'verbose_name': 'Registro Dental', 'verbose_name_plural': 'Registros Dentales'},
        ),
        migrations.AlterUniqueTogether(
            name='registrodental',
            unique_together={('paciente', 'pieza_dental')},
        ),
        migrations.AddField(
            model_name='registrodental',
            name='actualizado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_dentales_actualizados', to='odontologos.odontologo', verbose_name='Actualizado por'),
        ),
        migrations.AddField(
            model_name='registrodental',
            name='cara_distal',
            field=models.CharField(blank=True, choices=[('pendiente', 'Pendiente (Azul)'), ('realizado', 'Realizado (Rojo)')], max_length=20, null=True, verbose_name='Cara Distal'),
        ),
        migrations.AddField(
            model_name='registrodental',
            name='cara_lingual',
            field=models.CharField(blank=True, choices=[('pendiente', 'Pendiente (Azul)'), ('realizado', 'Realizado (Rojo)')], max_length=20, null=True, verbose_name='Cara Lingual/Palatina'),
        ),
        migrations.AddField(
            model_name='registrodental',
            name='cara_mesial',
            field=models.CharField(blank=True, choices=[('pendiente', 'Pendiente (Azul)'), ('realizado', 'Realizado (Rojo)')], max_length=20, null=True, verbose_name='Cara Mesial'),
        ),
        migrations.AddField(
            model_name='registrodental',
            name='cara_oclusal',
            field=models.CharField(blank=True, choices=[('pendiente', 'Pendiente (Azul)'), ('realizado', 'Realizado (Rojo)')], max_length=20, null=True, verbose_name='Cara Oclusal/Incisal'),
        ),
        migrations.AddField(
            model_name='registrodental',
            name='cara_vestibular',
            field=models.CharField(blank=True, choices=[('pendiente', 'Pendiente (Azul)'), ('realizado', 'Realizado (Rojo)')], max_length=20, null=True, verbose_name='Cara Vestibular'),
        ),
        migrations.AddField(
            model_name='registrodental',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='registrodental',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='registrodental',
            name='pieza_dental',
            field=models.IntegerField(choices=[(11, '11 - Incisivo Central Superior Derecho'), (12, '12 - Incisivo Lateral Superior Derecho'), (13, '13 - Canino Superior Derecho'), (14, '14 - Primer Premolar Superior Derecho'), (15, '15 - Segundo Premolar Superior Derecho'), (16, '16 - Primer Molar Superior Derecho'), (17, '17 - Segundo Molar Superior Derecho'), (18, '18 - Tercer Molar Superior Derecho'), (21, '21 - Incisivo Central Superior Izquierdo'), (22, '22 - Incisivo Lateral Superior Izquierdo'), (23, '23 - Canino Superior Izquierdo'), (24, '24 - Primer Premolar Superior Izquierdo'), (25, '25 - Segundo Premolar Superior Izquierdo'), (26, '26 - Primer Molar Superior Izquierdo'), (27, '27 - Segundo Molar Superior Izquierdo'), (28, '28 - Tercer Molar Superior Izquierdo'), (31, '31 - Incisivo Central Inferior Izquierdo'), (32, '32 - Incisivo Lateral Inferior Izquierdo'), (33, '33 - Canino Inferior Izquierdo'), (34, '34 - Primer Premolar Inferior Izquierdo'), (35, '35 - Segundo Premolar Inferior Izquierdo'), (36, '36 - Primer Molar Inferior Izquierdo'), (37, '37 - Segundo Molar Inferior Izquierdo'), (38, '38 - Tercer Molar Inferior Izquierdo'), (41, '41 - Incisivo Central Inferior Derecho'), (42, '42 - Incisivo Lateral Inferior Derecho'), (43, '43 - Canino Inferior Derecho'), (44, '44 - Primer Premolar Inferior Derecho'), (45, '45 - Segundo Premolar Inferior Derecho'), (46, '46 - Primer Molar Inferior Derecho'), (47, '47 - Segundo Molar Inferior Derecho'), (48, '48 - Tercer Molar Inferior Derecho'), (51, '51 - Incisivo Central Superior Derecho Temporal'), (52, '52 - Incisivo Lateral Superior Derecho Temporal'), (53, '53 - Canino Superior Derecho Temporal'), (54, '54 - Primer Molar Superior Derecho Temporal'), (55, '55 - Segundo Molar Superior Derecho Temporal'), (61, '61 - Incisivo Central Superior Izquierdo Temporal'), (62, '62 - Incisivo Lateral Superior Izquierdo Temporal'), (63, '63 - Canino Superior Izquierdo Temporal'), (64, '64 - Primer Molar Superior Izquierdo Temporal'), (65, '65 - Segundo Molar Superior Izquierdo Temporal'), (71, '71 - Incisivo Central Inferior Izquierdo Temporal'), (72, '72 - Incisivo Lateral Inferior Izquierdo Temporal'), (73, '73 - Canino Inferior Izquierdo Temporal'), (74, '74 - Primer Molar Inferior Izquierdo Temporal'), (75, '75 - Segundo Molar Inferior Izquierdo Temporal'), (81, '81 - Incisivo Central Inferior Derecho Temporal'), (82, '82 - Incisivo Lateral Inferior Derecho Temporal'), (83, '83 - Canino Inferior Derecho Temporal'), (84, '84 - Primer Molar Inferior Derecho Temporal'), (85, '85 - Segundo Molar Inferior Derecho Temporal')], verbose_name='Pieza Dental'),
        ),
        migrations.RemoveField(
            model_name='registrodental',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='registrodental',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='registrodental',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='registrodental',
            name='odontologo',
        ),
    ]
