# Generated by Django 6.0.1 on 2026-02-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0012_alter_registrodental_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodental',
            name='estado_pieza',
            field=models.CharField(choices=[('normal', 'Normal'), ('ausente', 'Ausente (X Roja)'), ('extraccion', 'Extracción Indicada (X Azul)'), ('corona_realizada', 'Corona Realizada (Círculo Rojo)'), ('corona_pendiente', 'Corona Pendiente (Círculo Azul)'), ('implante', 'Implante (I)'), ('absceso', 'Absceso/Fístula (Círculo Azul)')], default='normal', max_length=30, verbose_name='Estado de la Pieza'),
        ),
        migrations.AlterField(
            model_name='registrodental',
            name='cara_distal',
            field=models.JSONField(blank=True, null=True, verbose_name='Cara Distal'),
        ),
        migrations.AlterField(
            model_name='registrodental',
            name='cara_lingual',
            field=models.JSONField(blank=True, null=True, verbose_name='Cara Lingual/Palatina'),
        ),
        migrations.AlterField(
            model_name='registrodental',
            name='cara_mesial',
            field=models.JSONField(blank=True, null=True, verbose_name='Cara Mesial'),
        ),
        migrations.AlterField(
            model_name='registrodental',
            name='cara_oclusal',
            field=models.JSONField(blank=True, null=True, verbose_name='Cara Oclusal/Incisal'),
        ),
        migrations.AlterField(
            model_name='registrodental',
            name='cara_vestibular',
            field=models.JSONField(blank=True, null=True, verbose_name='Cara Vestibular'),
        ),
    ]
