# Generated by Django 6.0.1 on 2026-02-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0013_registrodental_estado_pieza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrodental',
            name='estado_pieza',
            field=models.CharField(choices=[('normal', 'Normal'), ('ausente', 'Ausente (X Roja)'), ('extraccion', 'Extracción Indicada (X Azul)'), ('tc_realizado', 'Tratamiento de Conducto Realizado (TC Rojo)'), ('tc_pendiente', 'Tratamiento de Conducto Pendiente (TC Azul)'), ('corona_realizada', 'Corona Realizada (Círculo Rojo)'), ('corona_pendiente', 'Corona Pendiente (Círculo Azul)'), ('implante', 'Implante (I)'), ('restauracion_total', 'Restauración Total'), ('absceso', 'Absceso/Fístula (Círculo Azul)')], default='normal', max_length=30, verbose_name='Estado de la Pieza'),
        ),
    ]
