# Generated by Django 6.0.1 on 2026-02-20 18:58

from django.db import migrations, models


def convertir_estado_pieza_a_array(apps, schema_editor):
    """Convertir valores de string a array"""
    RegistroDental = apps.get_model('pacientes', 'RegistroDental')
    for registro in RegistroDental.objects.all():
        if registro.estado_pieza and isinstance(registro.estado_pieza, str):
            # Si el estado es 'normal', convertir a array vacío
            if registro.estado_pieza == 'normal':
                registro.estado_pieza = []
            else:
                # Convertir el string a array con un solo elemento
                registro.estado_pieza = [registro.estado_pieza]
            registro.save()


def revertir_conversion(apps, schema_editor):
    """Revertir la conversión si es necesario"""
    RegistroDental = apps.get_model('pacientes', 'RegistroDental')
    for registro in RegistroDental.objects.all():
        if registro.estado_pieza and isinstance(registro.estado_pieza, list):
            # Tomar el primer elemento del array
            if len(registro.estado_pieza) > 0:
                registro.estado_pieza = registro.estado_pieza[0]
            else:
                registro.estado_pieza = 'normal'
            registro.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0014_alter_registrodental_estado_pieza'),
    ]

    operations = [
        migrations.RunPython(convertir_estado_pieza_a_array, revertir_conversion),
        migrations.AlterField(
            model_name='registrodental',
            name='estado_pieza',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Estados de la Pieza'),
        ),
    ]
