# Generated by Django 6.0.1 on 2026-02-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0015_alter_registrodental_estado_pieza'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodental',
            name='puente',
            field=models.JSONField(blank=True, help_text='Información del puente si esta pieza es pilar', null=True, verbose_name='Puente Dental'),
        ),
    ]
