# Generated by Django 6.0.1 on 2026-02-24 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologos', '0006_odontologo_estado_odontologo_fecha_aprobacion_and_more'),
        ('pacientes', '0016_registrodental_puente'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='creado_por_odontologo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_creados', to='odontologos.odontologo', verbose_name='Creado por odontólogo'),
        ),
    ]
