# Generated by Django 6.0.1 on 2026-03-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0017_visible_turno_creado_por_odontologo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodental',
            name='descripcion_general',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción general del odontograma'),
        ),
    ]
