# Generated by Django 6.0.1 on 2026-03-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologos', '0006_odontologo_estado_odontologo_fecha_aprobacion_and_more'),
        ('pacientes', '0018_registrodental_descripcion_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='odontologos_asignados',
            field=models.ManyToManyField(blank=True, related_name='pacientes_asignados', to='odontologos.odontologo', verbose_name='Odontólogos asignados'),
        ),
    ]
