# Generated by Django 6.0.1 on 2026-03-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0025_fix_odontograma_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientoarchivo',
            name='tamano',
            field=models.BigIntegerField(default=0, help_text='Tamaño del archivo en bytes para control de cuota', verbose_name='Tamaño del archivo (bytes)'),
        ),
    ]
