# Generated by Django 5.2.7 on 2026-02-06 19:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologos', '0003_alter_odontologo_id'),
        ('pacientes', '0003_alter_paciente_id'),
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['fecha_hora'], 'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
        migrations.AddField(
            model_name='turno',
            name='duracion_minutos',
            field=models.IntegerField(default=30, verbose_name='Duración (minutos)'),
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('completado', 'Completado')], default='disponible', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha_hora',
            field=models.DateTimeField(verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='motivo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo/Observaciones'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='odontologo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='odontologos.odontologo', verbose_name='Odontólogo'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='pacientes.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together={('odontologo', 'fecha_hora')},
        ),
    ]
