# Generated by Django 6.0.1 on 2026-02-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_alter_turno_options_turno_duracion_minutos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
