# Generated by Django 5.2.7 on 2026-02-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_alter_turno_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='apellido_paciente_manual',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido del paciente'),
        ),
        migrations.AddField(
            model_name='turno',
            name='nombre_paciente_manual',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del paciente'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
