# Generated by Django 5.2.7 on 2026-02-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_turno_apellido_paciente_manual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='telefono_paciente_manual',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del paciente'),
        ),
    ]
