# Generated by Django 6.0.1 on 2026-02-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0005_turno_telefono_paciente_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
