# Generated by Django 6.0.1 on 2026-02-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0006_alter_turno_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='visible',
            field=models.BooleanField(default=True, help_text='Si está desactivado, el turno solo es visible para el odontólogo (modo agenda privado)', verbose_name='Visible para pacientes'),
        ),
    ]
