# Generated by Django 6.0.1 on 2026-03-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0007_visible_turno_creado_por_odontologo'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='recordatorio_enviado',
            field=models.BooleanField(default=False, help_text='Indica si ya se envió el recordatorio por email para este turno', verbose_name='Recordatorio enviado'),
        ),
    ]
