# Generated by Django 6.0.1 on 2026-09-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0008_turno_recordatorio_enviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='email_paciente_manual',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del paciente'),
        ),
        migrations.AddField(
            model_name='turno',
            name='origen',
            field=models.CharField(choices=[('consultorio', 'Cargado por el consultorio'), ('online', 'Reserva online')], db_default='consultorio', default='consultorio', max_length=15, verbose_name='Origen'),
        ),
        migrations.AddField(
            model_name='turno',
            name='token_cancelacion',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Token para cancelar'),
        ),
    ]
