# Generated by Django 6.0.1 on 2026-02-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('paciente', 'Paciente'), ('odontologo', 'Odontólogo'), ('admin', 'Administrador')], default='paciente', max_length=20),
        ),
    ]
