# Generated by Django 6.0.1 on 2026-02-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cuenta_completa',
            field=models.BooleanField(default=True, help_text='False si fue creado por odontólogo sin email', verbose_name='Cuenta Completa'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tipo_registro',
            field=models.CharField(choices=[('autoregistro', 'Auto-registro'), ('odontologo', 'Creado por Odontólogo')], default='autoregistro', max_length=20, verbose_name='Tipo de Registro'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
    ]
